site:
  production_url: "http://bash.gelistiriciyiz.biz"
  title: "Bash Püf Noktaları"
  subtitle: "Bash ile ilgili Türkçe püf noktaları"
  tag_line: "Gündelik Hayatta Bash"
  description: "Bash ile ilgili Türkçe püf noktaları"
  logo: "logo.png"
  cover_image: "cover.jpg"
  social:
    twitter: "bash_tips_tr"
    # facebook: ""
  company:
    name: "Geliştiriciyiz.biz"
    url: "http://gelistiriciyiz.biz/"
  product:
    name: "GELİŞTİRİCİYİZ.BİZ"
    url: "http://gelistiriciyiz.biz/"
  main_author:
    name: "Uğur Özyılmazel"
    email: "ugurozyilmazel@gmail.com"
    link: "http://ugur.ozyilmazel.com"
    bio: "Yazılım Geliştiricisi"